SELECT ROUTE, CONCAT(FORMAT(SUM(D_BETWEEN_DIST), 1)+0, 'km') AS TOTAL_DISTANCE, CONCAT(FORMAT(AVG(D_BETWEEN_DIST), 2)+0, 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC;